unbind C-b
unbind -n C-r
set-option -g prefix C-t
bind C-t send-prefix

set -g base-index 1
set -g mouse on

# panes
bind r split-window -h
bind b split-window -v
bind j select-pane -D
bind k select-pane -U
bind h select-pane -L
bind l select-pane -R

# windows
bind t new-window -n 'terminal'
bind K next-window
bind J previous-window

# Statusbar Color Palette
set-option -g -u status-justify
set-option -g status-bg "blue"
set-option -g -u status-fg
set-option -g -u status-left-length
set-option -g -u status-right-length 

# session bindings
unbind 1
unbind 2
unbind 3
unbind 4
unbind 5

bind 1 switch-client -t cp
bind 2 switch-client -t contest
bind 3 switch-client -t c++
bind 4 switch-client -t dsa
bind 5 switch-client -t cses
